// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPXcbrhzlC8zmnnRzez6wTyRYC0DbvrGA',
    appId: '1:294508743526:web:cc83494b171f8fe96256a7',
    messagingSenderId: '294508743526',
    projectId: 'csa-training',
    authDomain: 'csa-training.firebaseapp.com',
    storageBucket: 'csa-training.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbmqic2W5JYAIeVti7EbxVI9_Xr_yMgCg',
    appId: '1:294508743526:android:0dfc2265811f60496256a7',
    messagingSenderId: '294508743526',
    projectId: 'csa-training',
    storageBucket: 'csa-training.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0uBgPks7X365CmjrdZjg9N7t9pHTjE-Y',
    appId: '1:294508743526:ios:844c565c83e36bd86256a7',
    messagingSenderId: '294508743526',
    projectId: 'csa-training',
    storageBucket: 'csa-training.appspot.com',
    iosBundleId: 'com.example.csaTrainingKit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0uBgPks7X365CmjrdZjg9N7t9pHTjE-Y',
    appId: '1:294508743526:ios:504e84b24dd07a296256a7',
    messagingSenderId: '294508743526',
    projectId: 'csa-training',
    storageBucket: 'csa-training.appspot.com',
    iosBundleId: 'com.example.csaTrainingKit.RunnerTests',
  );
}
